###### 🌏 ###### 💬 ######
# All my public-accessible Software-Content aren't underlying any Software-License. It's Free-Software.
# You can use my Code as you want — my only Wish is: mark me as Original-Creator of your Derivation. But you mustn't. :)
#
# My Intention of creating/publishing Free-Software is to help our Public Society.
# In this particular Case our newly-created "Computer-World". I mean everything regarding complex IT-Systems.
#
# made with ❤ by Jeremy Krüger (jkr.one). 😊
###### 🌏 ###### 💬 ######
services:
  - docker:dind

cache:
  paths:
    - .m2

variables:
  DOCKER_TLS_CERTDIR: ''
  DOCKER_DRIVER: overlay2
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build-and-test
  - deployment

Maven (Build & Run all Tests):
  stage: build-and-test
  image: maven:3.8.1-openjdk-11-slim
  script:
    - mvn -Dmaven.repo.local=./.m2/repository clean test verify

Start Development-Deployment:
  stage: deployment
  image: alpine:latest
  only:
    refs:
      - development
  script:
    # Preparation.
    - apk add --no-cache bash openssh sshpass
    # General-Execution.
    - deployment-utils/gitlab-deployment-scripts/ssh-deployment-script.sh "${SSH_DEPLOYMENT_HOST}" "${SSH_DEPLOYMENT_USER}" "${SSH_DEPLOYMENT_PASS}" "${SSH_DEPLOYMENT_LOCATION}" "production" "production"

Start Production-Deployment:
  stage: deployment
  image: alpine:latest
  only:
    refs:
      - production
  script:
    # Preparation.
    - apk add --no-cache bash openssh sshpass
    # General-Execution.
    - deployment-utils/gitlab-deployment-scripts/ssh-deployment-script.sh "${SSH_DEPLOYMENT_HOST}" "${SSH_DEPLOYMENT_USER}" "${SSH_DEPLOYMENT_PASS}" "${SSH_DEPLOYMENT_LOCATION}" "development" "development"
