###### 🌏 ###### 💬 ######
# All my public-accessible Software-Content aren't underlying any Software-License. It's Free-Software.
# You can use my Code as you want — my only Wish is: mark me as Original-Creator of your Derivation. But you mustn't. :)
#
# My Intention of creating/publishing Free-Software is to help our Public Society.
# In this particular Case our newly-created "Computer-World". I mean everything regarding complex IT-Systems.
#
# made for jkrsoftware.de as Versioning- and Deployment-System.
# made with ❤ by Jeremy Krüger (jkr.one). 😊
###### 🌏 ###### 💬 ######
version: '3'
services:
  springapp:
    build: .
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_PROJECT_NAME}-springapp.entrypoints=web"
      - "traefik.http.routers.${SERVICE_PROJECT_NAME}-springapp.rule=Host(`${SERVICE_HOST}`)"
      - "traefik.http.middlewares.${SERVICE_PROJECT_NAME}-springapp-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${SERVICE_PROJECT_NAME}-springapp.middlewares=${SERVICE_PROJECT_NAME}-springapp-https-redirect"
      - "traefik.http.routers.${SERVICE_PROJECT_NAME}-springapp-secure.entrypoints=websecure"
      - "traefik.http.routers.${SERVICE_PROJECT_NAME}-springapp-secure.rule=Host(`${SERVICE_HOST}`)"
      - "traefik.http.routers.${SERVICE_PROJECT_NAME}-springapp-secure.tls=true"
      - "traefik.http.routers.${SERVICE_PROJECT_NAME}-springapp-secure.tls.certresolver=myresolver"
      - "traefik.http.routers.${SERVICE_PROJECT_NAME}-springapp-secure.service=${SERVICE_PROJECT_NAME}-springapp"
      - "traefik.http.services.${SERVICE_PROJECT_NAME}-springapp.loadbalancer.server.port=8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${CURRENT_ENVIRONMENT}
    networks:
      web:

networks:
  web:
    external: true